apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.param_injector.service.service_name }}
spec:
  selector:
    app: {{ .Values.param_injector.service.deployment_name }}
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort

